// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhe4kMXxh2BeDjJptohcov6eGzRomkP1U',
    appId: '1:1079296696605:web:47929d883300bc59c241f4',
    messagingSenderId: '1079296696605',
    projectId: 'myapp-66120',
    authDomain: 'myapp-66120.firebaseapp.com',
    storageBucket: 'myapp-66120.appspot.com',
    measurementId: 'G-KCJL741EL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7oKh2AsOct2qK-ZvH5KNBPOv0z9yYE3o',
    appId: '1:1079296696605:android:7051d09e10fc6ec7c241f4',
    messagingSenderId: '1079296696605',
    projectId: 'myapp-66120',
    storageBucket: 'myapp-66120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNE-O-_Gjtz9cJ6P46H4dQwFavVP6AXyo',
    appId: '1:1079296696605:ios:184af0f7ab7bb2acc241f4',
    messagingSenderId: '1079296696605',
    projectId: 'myapp-66120',
    storageBucket: 'myapp-66120.appspot.com',
    iosBundleId: 'com.yashsapplication.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNE-O-_Gjtz9cJ6P46H4dQwFavVP6AXyo',
    appId: '1:1079296696605:ios:57bdafb38cb988fac241f4',
    messagingSenderId: '1079296696605',
    projectId: 'myapp-66120',
    storageBucket: 'myapp-66120.appspot.com',
    iosBundleId: 'com.yashsapplication.app.RunnerTests',
  );
}
